### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [36]:
import numpy as np

def create_array(N):
    arr=np.arange(N)
    return(arr[::-1])

print(create_array(5))

[4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [47]:
import numpy as np
def create_matrix(N):
    x=np.diag(create_array(10+1), k=0)
    return x, sum(np.diagonal(x))
matrix, sum_diag = create_matrix(10)
print(f'Диагональная матрица:\n{matrix}\nСумма значений по диагонали = {sum_diag}')

Диагональная матрица:
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Сумма значений по диагонали = 55


### Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [75]:
from numpy import linalg
a = np.array( 
    [
        [4, 2,1],
        [1,3, 0],
        [0,5,4]
    ] 
)
b=np.array([4,12,-3])

x,y,z =linalg.solve(a, b)
print(f'x={round(x,2)}, y={round(y,2)}, z={round(z,2)}')
np.allclose( np.dot(a, np.array([x,y,z])), b ) #проверка решения

x=0.47, y=3.84, z=-5.56


True

### Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”


In [109]:
users_stats = np.array(
    [
        [1, 2, 1, 0, 0, 0, 0],
        [2, 1, 1, 2, 1, 0, 0],
        [3, 2, 0, 1, 0, 0, 0],
        [4, 1, 1, 2, 1, 0, 1],
        [5, 0, 0, 1, 2, 0, 0],
        [6, 0, 0, 0, 0, 0, 5],
        [7, 1, 0, 0, 0, 0, 0],
        [8, 0, 1, 1, 0, 0, 0],
        [9, 0, 0, 0, 1, 1, 3],
        [10, 1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
max_cos=0
for users_stat in users_stats:
    aLength = np.linalg.norm( next_user_stats )
    bLength = np.linalg.norm( users_stat[1::])
    cos = np.dot( next_user_stats, users_stat[1::] ) / ( aLength * bLength )
    if cos > max_cos:
        max_cos=cos
        similar_user=users_stat[0]

print(f'Cамый похожий пользователь id {similar_user}')

Cамый похожий пользователь id 8
